#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice.h"
#include "cydevice_trm.h"

/* up */
#define up__0__INTTYPE CYREG_PICU3_INTTYPE4
#define up__0__MASK 0x10u
#define up__0__PC CYREG_PRT3_PC4
#define up__0__PORT 3u
#define up__0__SHIFT 4u
#define up__AG CYREG_PRT3_AG
#define up__AMUX CYREG_PRT3_AMUX
#define up__BIE CYREG_PRT3_BIE
#define up__BIT_MASK CYREG_PRT3_BIT_MASK
#define up__BYP CYREG_PRT3_BYP
#define up__CTL CYREG_PRT3_CTL
#define up__DM0 CYREG_PRT3_DM0
#define up__DM1 CYREG_PRT3_DM1
#define up__DM2 CYREG_PRT3_DM2
#define up__DR CYREG_PRT3_DR
#define up__INP_DIS CYREG_PRT3_INP_DIS
#define up__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU3_BASE
#define up__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define up__LCD_EN CYREG_PRT3_LCD_EN
#define up__MASK 0x10u
#define up__PORT 3u
#define up__PRT CYREG_PRT3_PRT
#define up__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define up__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define up__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define up__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define up__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define up__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define up__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define up__PS CYREG_PRT3_PS
#define up__SHIFT 4u
#define up__SLW CYREG_PRT3_SLW

/* ADC_ADC_SAR */
#define ADC_ADC_SAR__CLK CYREG_SAR0_CLK
#define ADC_ADC_SAR__CSR0 CYREG_SAR0_CSR0
#define ADC_ADC_SAR__CSR1 CYREG_SAR0_CSR1
#define ADC_ADC_SAR__CSR2 CYREG_SAR0_CSR2
#define ADC_ADC_SAR__CSR3 CYREG_SAR0_CSR3
#define ADC_ADC_SAR__CSR4 CYREG_SAR0_CSR4
#define ADC_ADC_SAR__CSR5 CYREG_SAR0_CSR5
#define ADC_ADC_SAR__CSR6 CYREG_SAR0_CSR6
#define ADC_ADC_SAR__PM_ACT_CFG CYREG_PM_ACT_CFG11
#define ADC_ADC_SAR__PM_ACT_MSK 0x01u
#define ADC_ADC_SAR__PM_STBY_CFG CYREG_PM_STBY_CFG11
#define ADC_ADC_SAR__PM_STBY_MSK 0x01u
#define ADC_ADC_SAR__SW0 CYREG_SAR0_SW0
#define ADC_ADC_SAR__SW2 CYREG_SAR0_SW2
#define ADC_ADC_SAR__SW3 CYREG_SAR0_SW3
#define ADC_ADC_SAR__SW4 CYREG_SAR0_SW4
#define ADC_ADC_SAR__SW6 CYREG_SAR0_SW6
#define ADC_ADC_SAR__TR0 CYREG_SAR0_TR0
#define ADC_ADC_SAR__WRK0 CYREG_SAR0_WRK0
#define ADC_ADC_SAR__WRK1 CYREG_SAR0_WRK1

/* ADC_IRQ */
#define ADC_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ADC_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ADC_IRQ__INTC_MASK 0x01u
#define ADC_IRQ__INTC_NUMBER 0u
#define ADC_IRQ__INTC_PRIOR_NUM 7u
#define ADC_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_0
#define ADC_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ADC_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* ADC_theACLK */
#define ADC_theACLK__CFG0 CYREG_CLKDIST_DCFG1_CFG0
#define ADC_theACLK__CFG1 CYREG_CLKDIST_DCFG1_CFG1
#define ADC_theACLK__CFG2 CYREG_CLKDIST_DCFG1_CFG2
#define ADC_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define ADC_theACLK__INDEX 0x01u
#define ADC_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_theACLK__PM_ACT_MSK 0x02u
#define ADC_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_theACLK__PM_STBY_MSK 0x02u

/* DAC_viDAC8 */
#define DAC_viDAC8__CR0 CYREG_DAC0_CR0
#define DAC_viDAC8__CR1 CYREG_DAC0_CR1
#define DAC_viDAC8__D CYREG_DAC0_D
#define DAC_viDAC8__PM_ACT_CFG CYREG_PM_ACT_CFG8
#define DAC_viDAC8__PM_ACT_MSK 0x01u
#define DAC_viDAC8__PM_STBY_CFG CYREG_PM_STBY_CFG8
#define DAC_viDAC8__PM_STBY_MSK 0x01u
#define DAC_viDAC8__STROBE CYREG_DAC0_STROBE
#define DAC_viDAC8__SW0 CYREG_DAC0_SW0
#define DAC_viDAC8__SW2 CYREG_DAC0_SW2
#define DAC_viDAC8__SW3 CYREG_DAC0_SW3
#define DAC_viDAC8__SW4 CYREG_DAC0_SW4
#define DAC_viDAC8__TR CYREG_DAC0_TR
#define DAC_viDAC8__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DAC0_M1
#define DAC_viDAC8__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DAC0_M2
#define DAC_viDAC8__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DAC0_M3
#define DAC_viDAC8__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DAC0_M4
#define DAC_viDAC8__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DAC0_M5
#define DAC_viDAC8__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DAC0_M6
#define DAC_viDAC8__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DAC0_M7
#define DAC_viDAC8__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DAC0_M8
#define DAC_viDAC8__TST CYREG_DAC0_TST

/* PWM_PWMUDB */
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB10_11_ACTL
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB10_11_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB10_11_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB10_11_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_B1_UDB10_11_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_MASK_MASK_REG CYREG_B1_UDB10_11_MSK
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_B1_UDB10_11_MSK
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_B1_UDB10_11_MSK
#define PWM_PWMUDB_genblk1_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB10_11_MSK
#define PWM_PWMUDB_genblk1_ctrlreg__7__MASK 0x80u
#define PWM_PWMUDB_genblk1_ctrlreg__7__POS 7
#define PWM_PWMUDB_genblk1_ctrlreg__CONTROL_AUX_CTL_REG CYREG_B1_UDB10_ACTL
#define PWM_PWMUDB_genblk1_ctrlreg__CONTROL_REG CYREG_B1_UDB10_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__CONTROL_ST_REG CYREG_B1_UDB10_ST_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__COUNT_REG CYREG_B1_UDB10_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__COUNT_ST_REG CYREG_B1_UDB10_ST_CTL
#define PWM_PWMUDB_genblk1_ctrlreg__MASK 0x80u
#define PWM_PWMUDB_genblk1_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define PWM_PWMUDB_genblk1_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define PWM_PWMUDB_genblk1_ctrlreg__PERIOD_REG CYREG_B1_UDB10_MSK
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_A0_REG CYREG_B1_UDB10_11_A0
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_A1_REG CYREG_B1_UDB10_11_A1
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_D0_REG CYREG_B1_UDB10_11_D0
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_D1_REG CYREG_B1_UDB10_11_D1
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_DP_AUX_CTL_REG CYREG_B1_UDB10_11_ACTL
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_F0_REG CYREG_B1_UDB10_11_F0
#define PWM_PWMUDB_sP8_pwmdp_u0__16BIT_F1_REG CYREG_B1_UDB10_11_F1
#define PWM_PWMUDB_sP8_pwmdp_u0__A0_A1_REG CYREG_B1_UDB10_A0_A1
#define PWM_PWMUDB_sP8_pwmdp_u0__A0_REG CYREG_B1_UDB10_A0
#define PWM_PWMUDB_sP8_pwmdp_u0__A1_REG CYREG_B1_UDB10_A1
#define PWM_PWMUDB_sP8_pwmdp_u0__D0_D1_REG CYREG_B1_UDB10_D0_D1
#define PWM_PWMUDB_sP8_pwmdp_u0__D0_REG CYREG_B1_UDB10_D0
#define PWM_PWMUDB_sP8_pwmdp_u0__D1_REG CYREG_B1_UDB10_D1
#define PWM_PWMUDB_sP8_pwmdp_u0__DP_AUX_CTL_REG CYREG_B1_UDB10_ACTL
#define PWM_PWMUDB_sP8_pwmdp_u0__F0_F1_REG CYREG_B1_UDB10_F0_F1
#define PWM_PWMUDB_sP8_pwmdp_u0__F0_REG CYREG_B1_UDB10_F0
#define PWM_PWMUDB_sP8_pwmdp_u0__F1_REG CYREG_B1_UDB10_F1
#define PWM_PWMUDB_sP8_pwmdp_u0__MSK_DP_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define PWM_PWMUDB_sP8_pwmdp_u0__PER_DP_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL

/* clk */
#define clk__CFG0 CYREG_CLKDIST_DCFG0_CFG0
#define clk__CFG1 CYREG_CLKDIST_DCFG0_CFG1
#define clk__CFG2 CYREG_CLKDIST_DCFG0_CFG2
#define clk__CFG2_SRC_SEL_MASK 0x07u
#define clk__INDEX 0x00u
#define clk__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define clk__PM_ACT_MSK 0x01u
#define clk__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define clk__PM_STBY_MSK 0x01u

/* drv */
#define drv__0__INTTYPE CYREG_PICU12_INTTYPE7
#define drv__0__MASK 0x80u
#define drv__0__PC CYREG_PRT12_PC7
#define drv__0__PORT 12u
#define drv__0__SHIFT 7u
#define drv__AG CYREG_PRT12_AG
#define drv__BIE CYREG_PRT12_BIE
#define drv__BIT_MASK CYREG_PRT12_BIT_MASK
#define drv__BYP CYREG_PRT12_BYP
#define drv__DM0 CYREG_PRT12_DM0
#define drv__DM1 CYREG_PRT12_DM1
#define drv__DM2 CYREG_PRT12_DM2
#define drv__DR CYREG_PRT12_DR
#define drv__INP_DIS CYREG_PRT12_INP_DIS
#define drv__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU12_BASE
#define drv__MASK 0x80u
#define drv__PORT 12u
#define drv__PRT CYREG_PRT12_PRT
#define drv__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define drv__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define drv__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define drv__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define drv__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define drv__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define drv__PS CYREG_PRT12_PS
#define drv__SHIFT 7u
#define drv__SIO_CFG CYREG_PRT12_SIO_CFG
#define drv__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define drv__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define drv__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define drv__SLW CYREG_PRT12_SLW

/* khz */
#define khz__CFG0 CYREG_CLKDIST_DCFG2_CFG0
#define khz__CFG1 CYREG_CLKDIST_DCFG2_CFG1
#define khz__CFG2 CYREG_CLKDIST_DCFG2_CFG2
#define khz__CFG2_SRC_SEL_MASK 0x07u
#define khz__INDEX 0x02u
#define khz__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define khz__PM_ACT_MSK 0x04u
#define khz__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define khz__PM_STBY_MSK 0x04u

/* seg */
#define seg__0__AG CYREG_PRT12_AG
#define seg__0__BIE CYREG_PRT12_BIE
#define seg__0__BIT_MASK CYREG_PRT12_BIT_MASK
#define seg__0__BYP CYREG_PRT12_BYP
#define seg__0__DM0 CYREG_PRT12_DM0
#define seg__0__DM1 CYREG_PRT12_DM1
#define seg__0__DM2 CYREG_PRT12_DM2
#define seg__0__DR CYREG_PRT12_DR
#define seg__0__INP_DIS CYREG_PRT12_INP_DIS
#define seg__0__INTTYPE CYREG_PICU12_INTTYPE5
#define seg__0__MASK 0x20u
#define seg__0__PC CYREG_PRT12_PC5
#define seg__0__PORT 12u
#define seg__0__PRT CYREG_PRT12_PRT
#define seg__0__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define seg__0__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define seg__0__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define seg__0__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define seg__0__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define seg__0__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define seg__0__PS CYREG_PRT12_PS
#define seg__0__SHIFT 5u
#define seg__0__SIO_CFG CYREG_PRT12_SIO_CFG
#define seg__0__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define seg__0__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define seg__0__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define seg__0__SLW CYREG_PRT12_SLW
#define seg__1__AG CYREG_PRT12_AG
#define seg__1__BIE CYREG_PRT12_BIE
#define seg__1__BIT_MASK CYREG_PRT12_BIT_MASK
#define seg__1__BYP CYREG_PRT12_BYP
#define seg__1__DM0 CYREG_PRT12_DM0
#define seg__1__DM1 CYREG_PRT12_DM1
#define seg__1__DM2 CYREG_PRT12_DM2
#define seg__1__DR CYREG_PRT12_DR
#define seg__1__INP_DIS CYREG_PRT12_INP_DIS
#define seg__1__INTTYPE CYREG_PICU12_INTTYPE4
#define seg__1__MASK 0x10u
#define seg__1__PC CYREG_PRT12_PC4
#define seg__1__PORT 12u
#define seg__1__PRT CYREG_PRT12_PRT
#define seg__1__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define seg__1__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define seg__1__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define seg__1__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define seg__1__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define seg__1__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define seg__1__PS CYREG_PRT12_PS
#define seg__1__SHIFT 4u
#define seg__1__SIO_CFG CYREG_PRT12_SIO_CFG
#define seg__1__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define seg__1__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define seg__1__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define seg__1__SLW CYREG_PRT12_SLW
#define seg__2__AG CYREG_PRT2_AG
#define seg__2__AMUX CYREG_PRT2_AMUX
#define seg__2__BIE CYREG_PRT2_BIE
#define seg__2__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__2__BYP CYREG_PRT2_BYP
#define seg__2__CTL CYREG_PRT2_CTL
#define seg__2__DM0 CYREG_PRT2_DM0
#define seg__2__DM1 CYREG_PRT2_DM1
#define seg__2__DM2 CYREG_PRT2_DM2
#define seg__2__DR CYREG_PRT2_DR
#define seg__2__INP_DIS CYREG_PRT2_INP_DIS
#define seg__2__INTTYPE CYREG_PICU2_INTTYPE7
#define seg__2__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__2__LCD_EN CYREG_PRT2_LCD_EN
#define seg__2__MASK 0x80u
#define seg__2__PC CYREG_PRT2_PC7
#define seg__2__PORT 2u
#define seg__2__PRT CYREG_PRT2_PRT
#define seg__2__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__2__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__2__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__2__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__2__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__2__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__2__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__2__PS CYREG_PRT2_PS
#define seg__2__SHIFT 7u
#define seg__2__SLW CYREG_PRT2_SLW
#define seg__3__AG CYREG_PRT2_AG
#define seg__3__AMUX CYREG_PRT2_AMUX
#define seg__3__BIE CYREG_PRT2_BIE
#define seg__3__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__3__BYP CYREG_PRT2_BYP
#define seg__3__CTL CYREG_PRT2_CTL
#define seg__3__DM0 CYREG_PRT2_DM0
#define seg__3__DM1 CYREG_PRT2_DM1
#define seg__3__DM2 CYREG_PRT2_DM2
#define seg__3__DR CYREG_PRT2_DR
#define seg__3__INP_DIS CYREG_PRT2_INP_DIS
#define seg__3__INTTYPE CYREG_PICU2_INTTYPE6
#define seg__3__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__3__LCD_EN CYREG_PRT2_LCD_EN
#define seg__3__MASK 0x40u
#define seg__3__PC CYREG_PRT2_PC6
#define seg__3__PORT 2u
#define seg__3__PRT CYREG_PRT2_PRT
#define seg__3__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__3__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__3__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__3__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__3__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__3__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__3__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__3__PS CYREG_PRT2_PS
#define seg__3__SHIFT 6u
#define seg__3__SLW CYREG_PRT2_SLW
#define seg__4__AG CYREG_PRT2_AG
#define seg__4__AMUX CYREG_PRT2_AMUX
#define seg__4__BIE CYREG_PRT2_BIE
#define seg__4__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__4__BYP CYREG_PRT2_BYP
#define seg__4__CTL CYREG_PRT2_CTL
#define seg__4__DM0 CYREG_PRT2_DM0
#define seg__4__DM1 CYREG_PRT2_DM1
#define seg__4__DM2 CYREG_PRT2_DM2
#define seg__4__DR CYREG_PRT2_DR
#define seg__4__INP_DIS CYREG_PRT2_INP_DIS
#define seg__4__INTTYPE CYREG_PICU2_INTTYPE4
#define seg__4__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__4__LCD_EN CYREG_PRT2_LCD_EN
#define seg__4__MASK 0x10u
#define seg__4__PC CYREG_PRT2_PC4
#define seg__4__PORT 2u
#define seg__4__PRT CYREG_PRT2_PRT
#define seg__4__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__4__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__4__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__4__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__4__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__4__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__4__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__4__PS CYREG_PRT2_PS
#define seg__4__SHIFT 4u
#define seg__4__SLW CYREG_PRT2_SLW
#define seg__5__AG CYREG_PRT2_AG
#define seg__5__AMUX CYREG_PRT2_AMUX
#define seg__5__BIE CYREG_PRT2_BIE
#define seg__5__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__5__BYP CYREG_PRT2_BYP
#define seg__5__CTL CYREG_PRT2_CTL
#define seg__5__DM0 CYREG_PRT2_DM0
#define seg__5__DM1 CYREG_PRT2_DM1
#define seg__5__DM2 CYREG_PRT2_DM2
#define seg__5__DR CYREG_PRT2_DR
#define seg__5__INP_DIS CYREG_PRT2_INP_DIS
#define seg__5__INTTYPE CYREG_PICU2_INTTYPE3
#define seg__5__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__5__LCD_EN CYREG_PRT2_LCD_EN
#define seg__5__MASK 0x08u
#define seg__5__PC CYREG_PRT2_PC3
#define seg__5__PORT 2u
#define seg__5__PRT CYREG_PRT2_PRT
#define seg__5__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__5__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__5__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__5__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__5__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__5__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__5__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__5__PS CYREG_PRT2_PS
#define seg__5__SHIFT 3u
#define seg__5__SLW CYREG_PRT2_SLW
#define seg__6__AG CYREG_PRT2_AG
#define seg__6__AMUX CYREG_PRT2_AMUX
#define seg__6__BIE CYREG_PRT2_BIE
#define seg__6__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__6__BYP CYREG_PRT2_BYP
#define seg__6__CTL CYREG_PRT2_CTL
#define seg__6__DM0 CYREG_PRT2_DM0
#define seg__6__DM1 CYREG_PRT2_DM1
#define seg__6__DM2 CYREG_PRT2_DM2
#define seg__6__DR CYREG_PRT2_DR
#define seg__6__INP_DIS CYREG_PRT2_INP_DIS
#define seg__6__INTTYPE CYREG_PICU2_INTTYPE2
#define seg__6__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__6__LCD_EN CYREG_PRT2_LCD_EN
#define seg__6__MASK 0x04u
#define seg__6__PC CYREG_PRT2_PC2
#define seg__6__PORT 2u
#define seg__6__PRT CYREG_PRT2_PRT
#define seg__6__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__6__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__6__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__6__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__6__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__6__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__6__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__6__PS CYREG_PRT2_PS
#define seg__6__SHIFT 2u
#define seg__6__SLW CYREG_PRT2_SLW
#define seg__7__AG CYREG_PRT2_AG
#define seg__7__AMUX CYREG_PRT2_AMUX
#define seg__7__BIE CYREG_PRT2_BIE
#define seg__7__BIT_MASK CYREG_PRT2_BIT_MASK
#define seg__7__BYP CYREG_PRT2_BYP
#define seg__7__CTL CYREG_PRT2_CTL
#define seg__7__DM0 CYREG_PRT2_DM0
#define seg__7__DM1 CYREG_PRT2_DM1
#define seg__7__DM2 CYREG_PRT2_DM2
#define seg__7__DR CYREG_PRT2_DR
#define seg__7__INP_DIS CYREG_PRT2_INP_DIS
#define seg__7__INTTYPE CYREG_PICU2_INTTYPE1
#define seg__7__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define seg__7__LCD_EN CYREG_PRT2_LCD_EN
#define seg__7__MASK 0x02u
#define seg__7__PC CYREG_PRT2_PC1
#define seg__7__PORT 2u
#define seg__7__PRT CYREG_PRT2_PRT
#define seg__7__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define seg__7__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define seg__7__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define seg__7__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define seg__7__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define seg__7__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define seg__7__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define seg__7__PS CYREG_PRT2_PS
#define seg__7__SHIFT 1u
#define seg__7__SLW CYREG_PRT2_SLW

/* DMA1 */
#define DMA1__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define DMA1__DRQ_NUMBER 0u
#define DMA1__NUMBEROF_TDS 0u
#define DMA1__PRIORITY 2u
#define DMA1__TERMIN_EN 0u
#define DMA1__TERMIN_SEL 0u
#define DMA1__TERMOUT0_EN 1u
#define DMA1__TERMOUT0_SEL 0u
#define DMA1__TERMOUT1_EN 0u
#define DMA1__TERMOUT1_SEL 0u

/* DMA2 */
#define DMA2__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define DMA2__DRQ_NUMBER 1u
#define DMA2__NUMBEROF_TDS 0u
#define DMA2__PRIORITY 2u
#define DMA2__TERMIN_EN 0u
#define DMA2__TERMIN_SEL 0u
#define DMA2__TERMOUT0_EN 0u
#define DMA2__TERMOUT0_SEL 0u
#define DMA2__TERMOUT1_EN 0u
#define DMA2__TERMOUT1_SEL 0u

/* down */
#define down__0__INTTYPE CYREG_PICU3_INTTYPE3
#define down__0__MASK 0x08u
#define down__0__PC CYREG_PRT3_PC3
#define down__0__PORT 3u
#define down__0__SHIFT 3u
#define down__AG CYREG_PRT3_AG
#define down__AMUX CYREG_PRT3_AMUX
#define down__BIE CYREG_PRT3_BIE
#define down__BIT_MASK CYREG_PRT3_BIT_MASK
#define down__BYP CYREG_PRT3_BYP
#define down__CTL CYREG_PRT3_CTL
#define down__DM0 CYREG_PRT3_DM0
#define down__DM1 CYREG_PRT3_DM1
#define down__DM2 CYREG_PRT3_DM2
#define down__DR CYREG_PRT3_DR
#define down__INP_DIS CYREG_PRT3_INP_DIS
#define down__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU3_BASE
#define down__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define down__LCD_EN CYREG_PRT3_LCD_EN
#define down__MASK 0x08u
#define down__PORT 3u
#define down__PRT CYREG_PRT3_PRT
#define down__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define down__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define down__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define down__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define down__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define down__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define down__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define down__PS CYREG_PRT3_PS
#define down__SHIFT 3u
#define down__SLW CYREG_PRT3_SLW

/* mode */
#define mode__0__INTTYPE CYREG_PICU3_INTTYPE5
#define mode__0__MASK 0x20u
#define mode__0__PC CYREG_PRT3_PC5
#define mode__0__PORT 3u
#define mode__0__SHIFT 5u
#define mode__AG CYREG_PRT3_AG
#define mode__AMUX CYREG_PRT3_AMUX
#define mode__BIE CYREG_PRT3_BIE
#define mode__BIT_MASK CYREG_PRT3_BIT_MASK
#define mode__BYP CYREG_PRT3_BYP
#define mode__CTL CYREG_PRT3_CTL
#define mode__DM0 CYREG_PRT3_DM0
#define mode__DM1 CYREG_PRT3_DM1
#define mode__DM2 CYREG_PRT3_DM2
#define mode__DR CYREG_PRT3_DR
#define mode__INP_DIS CYREG_PRT3_INP_DIS
#define mode__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU3_BASE
#define mode__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define mode__LCD_EN CYREG_PRT3_LCD_EN
#define mode__MASK 0x20u
#define mode__PORT 3u
#define mode__PRT CYREG_PRT3_PRT
#define mode__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define mode__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define mode__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define mode__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define mode__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define mode__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define mode__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define mode__PS CYREG_PRT3_PS
#define mode__SHIFT 5u
#define mode__SLW CYREG_PRT3_SLW

/* vout */
#define vout__0__INTTYPE CYREG_PICU3_INTTYPE1
#define vout__0__MASK 0x02u
#define vout__0__PC CYREG_PRT3_PC1
#define vout__0__PORT 3u
#define vout__0__SHIFT 1u
#define vout__AG CYREG_PRT3_AG
#define vout__AMUX CYREG_PRT3_AMUX
#define vout__BIE CYREG_PRT3_BIE
#define vout__BIT_MASK CYREG_PRT3_BIT_MASK
#define vout__BYP CYREG_PRT3_BYP
#define vout__CTL CYREG_PRT3_CTL
#define vout__DM0 CYREG_PRT3_DM0
#define vout__DM1 CYREG_PRT3_DM1
#define vout__DM2 CYREG_PRT3_DM2
#define vout__DR CYREG_PRT3_DR
#define vout__INP_DIS CYREG_PRT3_INP_DIS
#define vout__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU3_BASE
#define vout__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define vout__LCD_EN CYREG_PRT3_LCD_EN
#define vout__MASK 0x02u
#define vout__PORT 3u
#define vout__PRT CYREG_PRT3_PRT
#define vout__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define vout__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define vout__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define vout__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define vout__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define vout__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define vout__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define vout__PS CYREG_PRT3_PS
#define vout__SHIFT 1u
#define vout__SLW CYREG_PRT3_SLW

/* grid1 */
#define grid1__0__INTTYPE CYREG_PICU1_INTTYPE3
#define grid1__0__MASK 0x08u
#define grid1__0__PC CYREG_PRT1_PC3
#define grid1__0__PORT 1u
#define grid1__0__SHIFT 3u
#define grid1__AG CYREG_PRT1_AG
#define grid1__AMUX CYREG_PRT1_AMUX
#define grid1__BIE CYREG_PRT1_BIE
#define grid1__BIT_MASK CYREG_PRT1_BIT_MASK
#define grid1__BYP CYREG_PRT1_BYP
#define grid1__CTL CYREG_PRT1_CTL
#define grid1__DM0 CYREG_PRT1_DM0
#define grid1__DM1 CYREG_PRT1_DM1
#define grid1__DM2 CYREG_PRT1_DM2
#define grid1__DR CYREG_PRT1_DR
#define grid1__INP_DIS CYREG_PRT1_INP_DIS
#define grid1__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define grid1__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define grid1__LCD_EN CYREG_PRT1_LCD_EN
#define grid1__MASK 0x08u
#define grid1__PORT 1u
#define grid1__PRT CYREG_PRT1_PRT
#define grid1__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define grid1__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define grid1__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define grid1__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define grid1__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define grid1__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define grid1__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define grid1__PS CYREG_PRT1_PS
#define grid1__SHIFT 3u
#define grid1__SLW CYREG_PRT1_SLW

/* grid2 */
#define grid2__0__INTTYPE CYREG_PICU1_INTTYPE4
#define grid2__0__MASK 0x10u
#define grid2__0__PC CYREG_PRT1_PC4
#define grid2__0__PORT 1u
#define grid2__0__SHIFT 4u
#define grid2__AG CYREG_PRT1_AG
#define grid2__AMUX CYREG_PRT1_AMUX
#define grid2__BIE CYREG_PRT1_BIE
#define grid2__BIT_MASK CYREG_PRT1_BIT_MASK
#define grid2__BYP CYREG_PRT1_BYP
#define grid2__CTL CYREG_PRT1_CTL
#define grid2__DM0 CYREG_PRT1_DM0
#define grid2__DM1 CYREG_PRT1_DM1
#define grid2__DM2 CYREG_PRT1_DM2
#define grid2__DR CYREG_PRT1_DR
#define grid2__INP_DIS CYREG_PRT1_INP_DIS
#define grid2__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define grid2__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define grid2__LCD_EN CYREG_PRT1_LCD_EN
#define grid2__MASK 0x10u
#define grid2__PORT 1u
#define grid2__PRT CYREG_PRT1_PRT
#define grid2__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define grid2__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define grid2__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define grid2__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define grid2__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define grid2__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define grid2__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define grid2__PS CYREG_PRT1_PS
#define grid2__SHIFT 4u
#define grid2__SLW CYREG_PRT1_SLW

/* grid3 */
#define grid3__0__INTTYPE CYREG_PICU1_INTTYPE6
#define grid3__0__MASK 0x40u
#define grid3__0__PC CYREG_PRT1_PC6
#define grid3__0__PORT 1u
#define grid3__0__SHIFT 6u
#define grid3__AG CYREG_PRT1_AG
#define grid3__AMUX CYREG_PRT1_AMUX
#define grid3__BIE CYREG_PRT1_BIE
#define grid3__BIT_MASK CYREG_PRT1_BIT_MASK
#define grid3__BYP CYREG_PRT1_BYP
#define grid3__CTL CYREG_PRT1_CTL
#define grid3__DM0 CYREG_PRT1_DM0
#define grid3__DM1 CYREG_PRT1_DM1
#define grid3__DM2 CYREG_PRT1_DM2
#define grid3__DR CYREG_PRT1_DR
#define grid3__INP_DIS CYREG_PRT1_INP_DIS
#define grid3__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define grid3__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define grid3__LCD_EN CYREG_PRT1_LCD_EN
#define grid3__MASK 0x40u
#define grid3__PORT 1u
#define grid3__PRT CYREG_PRT1_PRT
#define grid3__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define grid3__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define grid3__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define grid3__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define grid3__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define grid3__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define grid3__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define grid3__PS CYREG_PRT1_PS
#define grid3__SHIFT 6u
#define grid3__SLW CYREG_PRT1_SLW

/* grid4 */
#define grid4__0__INTTYPE CYREG_PICU1_INTTYPE7
#define grid4__0__MASK 0x80u
#define grid4__0__PC CYREG_PRT1_PC7
#define grid4__0__PORT 1u
#define grid4__0__SHIFT 7u
#define grid4__AG CYREG_PRT1_AG
#define grid4__AMUX CYREG_PRT1_AMUX
#define grid4__BIE CYREG_PRT1_BIE
#define grid4__BIT_MASK CYREG_PRT1_BIT_MASK
#define grid4__BYP CYREG_PRT1_BYP
#define grid4__CTL CYREG_PRT1_CTL
#define grid4__DM0 CYREG_PRT1_DM0
#define grid4__DM1 CYREG_PRT1_DM1
#define grid4__DM2 CYREG_PRT1_DM2
#define grid4__DR CYREG_PRT1_DR
#define grid4__INP_DIS CYREG_PRT1_INP_DIS
#define grid4__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define grid4__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define grid4__LCD_EN CYREG_PRT1_LCD_EN
#define grid4__MASK 0x80u
#define grid4__PORT 1u
#define grid4__PRT CYREG_PRT1_PRT
#define grid4__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define grid4__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define grid4__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define grid4__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define grid4__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define grid4__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define grid4__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define grid4__PS CYREG_PRT1_PS
#define grid4__SHIFT 7u
#define grid4__SLW CYREG_PRT1_SLW

/* sense */
#define sense__0__INTTYPE CYREG_PICU15_INTTYPE1
#define sense__0__MASK 0x02u
#define sense__0__PC CYREG_IO_PC_PRT15_PC1
#define sense__0__PORT 15u
#define sense__0__SHIFT 1u
#define sense__AG CYREG_PRT15_AG
#define sense__AMUX CYREG_PRT15_AMUX
#define sense__BIE CYREG_PRT15_BIE
#define sense__BIT_MASK CYREG_PRT15_BIT_MASK
#define sense__BYP CYREG_PRT15_BYP
#define sense__CTL CYREG_PRT15_CTL
#define sense__DM0 CYREG_PRT15_DM0
#define sense__DM1 CYREG_PRT15_DM1
#define sense__DM2 CYREG_PRT15_DM2
#define sense__DR CYREG_PRT15_DR
#define sense__INP_DIS CYREG_PRT15_INP_DIS
#define sense__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU15_BASE
#define sense__LCD_COM_SEG CYREG_PRT15_LCD_COM_SEG
#define sense__LCD_EN CYREG_PRT15_LCD_EN
#define sense__MASK 0x02u
#define sense__PORT 15u
#define sense__PRT CYREG_PRT15_PRT
#define sense__PRTDSI__CAPS_SEL CYREG_PRT15_CAPS_SEL
#define sense__PRTDSI__DBL_SYNC_IN CYREG_PRT15_DBL_SYNC_IN
#define sense__PRTDSI__OE_SEL0 CYREG_PRT15_OE_SEL0
#define sense__PRTDSI__OE_SEL1 CYREG_PRT15_OE_SEL1
#define sense__PRTDSI__OUT_SEL0 CYREG_PRT15_OUT_SEL0
#define sense__PRTDSI__OUT_SEL1 CYREG_PRT15_OUT_SEL1
#define sense__PRTDSI__SYNC_OUT CYREG_PRT15_SYNC_OUT
#define sense__PS CYREG_PRT15_PS
#define sense__SHIFT 1u
#define sense__SLW CYREG_PRT15_SLW

/* Clock_1 */
#define Clock_1__CFG0 CYREG_CLKDIST_DCFG3_CFG0
#define Clock_1__CFG1 CYREG_CLKDIST_DCFG3_CFG1
#define Clock_1__CFG2 CYREG_CLKDIST_DCFG3_CFG2
#define Clock_1__CFG2_SRC_SEL_MASK 0x07u
#define Clock_1__INDEX 0x03u
#define Clock_1__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define Clock_1__PM_ACT_MSK 0x08u
#define Clock_1__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define Clock_1__PM_STBY_MSK 0x08u

/* clock_cmod */
#define clock_cmod_bsig_dp__A0_A1_REG CYREG_B1_UDB11_A0_A1
#define clock_cmod_bsig_dp__A0_REG CYREG_B1_UDB11_A0
#define clock_cmod_bsig_dp__A1_REG CYREG_B1_UDB11_A1
#define clock_cmod_bsig_dp__D0_D1_REG CYREG_B1_UDB11_D0_D1
#define clock_cmod_bsig_dp__D0_REG CYREG_B1_UDB11_D0
#define clock_cmod_bsig_dp__D1_REG CYREG_B1_UDB11_D1
#define clock_cmod_bsig_dp__DP_AUX_CTL_REG CYREG_B1_UDB11_ACTL
#define clock_cmod_bsig_dp__F0_F1_REG CYREG_B1_UDB11_F0_F1
#define clock_cmod_bsig_dp__F0_REG CYREG_B1_UDB11_F0
#define clock_cmod_bsig_dp__F1_REG CYREG_B1_UDB11_F1
#define clock_cmod_bsig_dp__MSK_DP_AUX_CTL_REG CYREG_B1_UDB11_MSK_ACTL
#define clock_cmod_bsig_dp__PER_DP_AUX_CTL_REG CYREG_B1_UDB11_MSK_ACTL
#define clock_cmod_div1_counter__CONTROL_AUX_CTL_REG CYREG_B1_UDB11_ACTL
#define clock_cmod_div1_counter__CONTROL_REG CYREG_B1_UDB11_CTL
#define clock_cmod_div1_counter__CONTROL_ST_REG CYREG_B1_UDB11_ST_CTL
#define clock_cmod_div1_counter__COUNT_REG CYREG_B1_UDB11_CTL
#define clock_cmod_div1_counter__COUNT_ST_REG CYREG_B1_UDB11_ST_CTL
#define clock_cmod_div1_counter__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB11_MSK_ACTL
#define clock_cmod_div1_counter__PER_CTL_AUX_CTL_REG CYREG_B1_UDB11_MSK_ACTL
#define clock_cmod_div1_counter__PERIOD_REG CYREG_B1_UDB11_MSK
#define clock_cmod_div2_counter__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB09_10_ACTL
#define clock_cmod_div2_counter__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB09_10_CTL
#define clock_cmod_div2_counter__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB09_10_CTL
#define clock_cmod_div2_counter__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB09_10_CTL
#define clock_cmod_div2_counter__16BIT_COUNT_COUNT_REG CYREG_B1_UDB09_10_CTL
#define clock_cmod_div2_counter__16BIT_MASK_MASK_REG CYREG_B1_UDB09_10_MSK
#define clock_cmod_div2_counter__16BIT_MASK_PERIOD_REG CYREG_B1_UDB09_10_MSK
#define clock_cmod_div2_counter__16BIT_PERIOD_MASK_REG CYREG_B1_UDB09_10_MSK
#define clock_cmod_div2_counter__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB09_10_MSK
#define clock_cmod_div2_counter__CONTROL_AUX_CTL_REG CYREG_B1_UDB09_ACTL
#define clock_cmod_div2_counter__CONTROL_REG CYREG_B1_UDB09_CTL
#define clock_cmod_div2_counter__CONTROL_ST_REG CYREG_B1_UDB09_ST_CTL
#define clock_cmod_div2_counter__COUNT_REG CYREG_B1_UDB09_CTL
#define clock_cmod_div2_counter__COUNT_ST_REG CYREG_B1_UDB09_ST_CTL
#define clock_cmod_div2_counter__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB09_MSK_ACTL
#define clock_cmod_div2_counter__PER_CTL_AUX_CTL_REG CYREG_B1_UDB09_MSK_ACTL
#define clock_cmod_div2_counter__PERIOD_REG CYREG_B1_UDB09_MSK
#define clock_cmod_div2_counter_ST__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB09_10_ACTL
#define clock_cmod_div2_counter_ST__16BIT_STATUS_REG CYREG_B1_UDB09_10_ST
#define clock_cmod_div2_counter_ST__MASK_REG CYREG_B1_UDB09_MSK
#define clock_cmod_div2_counter_ST__MASK_ST_AUX_CTL_REG CYREG_B1_UDB09_MSK_ACTL
#define clock_cmod_div2_counter_ST__PER_ST_AUX_CTL_REG CYREG_B1_UDB09_MSK_ACTL
#define clock_cmod_div2_counter_ST__STATUS_AUX_CTL_REG CYREG_B1_UDB09_ACTL
#define clock_cmod_div2_counter_ST__STATUS_CNT_REG CYREG_B1_UDB09_ST_CTL
#define clock_cmod_div2_counter_ST__STATUS_CONTROL_REG CYREG_B1_UDB09_ST_CTL
#define clock_cmod_div2_counter_ST__STATUS_REG CYREG_B1_UDB09_ST
#define clock_cmod_div3_counter__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB08_09_ACTL
#define clock_cmod_div3_counter__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB08_09_CTL
#define clock_cmod_div3_counter__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB08_09_CTL
#define clock_cmod_div3_counter__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB08_09_CTL
#define clock_cmod_div3_counter__16BIT_COUNT_COUNT_REG CYREG_B1_UDB08_09_CTL
#define clock_cmod_div3_counter__16BIT_MASK_MASK_REG CYREG_B1_UDB08_09_MSK
#define clock_cmod_div3_counter__16BIT_MASK_PERIOD_REG CYREG_B1_UDB08_09_MSK
#define clock_cmod_div3_counter__16BIT_PERIOD_MASK_REG CYREG_B1_UDB08_09_MSK
#define clock_cmod_div3_counter__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB08_09_MSK
#define clock_cmod_div3_counter__CONTROL_AUX_CTL_REG CYREG_B1_UDB08_ACTL
#define clock_cmod_div3_counter__CONTROL_REG CYREG_B1_UDB08_CTL
#define clock_cmod_div3_counter__CONTROL_ST_REG CYREG_B1_UDB08_ST_CTL
#define clock_cmod_div3_counter__COUNT_REG CYREG_B1_UDB08_CTL
#define clock_cmod_div3_counter__COUNT_ST_REG CYREG_B1_UDB08_ST_CTL
#define clock_cmod_div3_counter__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_div3_counter__PER_CTL_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_div3_counter__PERIOD_REG CYREG_B1_UDB08_MSK
#define clock_cmod_div3_counter_ST__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB08_09_ACTL
#define clock_cmod_div3_counter_ST__16BIT_STATUS_REG CYREG_B1_UDB08_09_ST
#define clock_cmod_div3_counter_ST__MASK_REG CYREG_B1_UDB08_MSK
#define clock_cmod_div3_counter_ST__MASK_ST_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_div3_counter_ST__PER_ST_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_div3_counter_ST__STATUS_AUX_CTL_REG CYREG_B1_UDB08_ACTL
#define clock_cmod_div3_counter_ST__STATUS_CNT_REG CYREG_B1_UDB08_ST_CTL
#define clock_cmod_div3_counter_ST__STATUS_CONTROL_REG CYREG_B1_UDB08_ST_CTL
#define clock_cmod_div3_counter_ST__STATUS_REG CYREG_B1_UDB08_ST
#define clock_cmod_hour_counter__16BIT_A0_REG CYREG_B1_UDB08_09_A0
#define clock_cmod_hour_counter__16BIT_A1_REG CYREG_B1_UDB08_09_A1
#define clock_cmod_hour_counter__16BIT_D0_REG CYREG_B1_UDB08_09_D0
#define clock_cmod_hour_counter__16BIT_D1_REG CYREG_B1_UDB08_09_D1
#define clock_cmod_hour_counter__16BIT_DP_AUX_CTL_REG CYREG_B1_UDB08_09_ACTL
#define clock_cmod_hour_counter__16BIT_F0_REG CYREG_B1_UDB08_09_F0
#define clock_cmod_hour_counter__16BIT_F1_REG CYREG_B1_UDB08_09_F1
#define clock_cmod_hour_counter__A0_A1_REG CYREG_B1_UDB08_A0_A1
#define clock_cmod_hour_counter__A0_REG CYREG_B1_UDB08_A0
#define clock_cmod_hour_counter__A1_REG CYREG_B1_UDB08_A1
#define clock_cmod_hour_counter__D0_D1_REG CYREG_B1_UDB08_D0_D1
#define clock_cmod_hour_counter__D0_REG CYREG_B1_UDB08_D0
#define clock_cmod_hour_counter__D1_REG CYREG_B1_UDB08_D1
#define clock_cmod_hour_counter__DP_AUX_CTL_REG CYREG_B1_UDB08_ACTL
#define clock_cmod_hour_counter__F0_F1_REG CYREG_B1_UDB08_F0_F1
#define clock_cmod_hour_counter__F0_REG CYREG_B1_UDB08_F0
#define clock_cmod_hour_counter__F1_REG CYREG_B1_UDB08_F1
#define clock_cmod_hour_counter__MSK_DP_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_hour_counter__PER_DP_AUX_CTL_REG CYREG_B1_UDB08_MSK_ACTL
#define clock_cmod_minute_counter__16BIT_A0_REG CYREG_B0_UDB08_09_A0
#define clock_cmod_minute_counter__16BIT_A1_REG CYREG_B0_UDB08_09_A1
#define clock_cmod_minute_counter__16BIT_D0_REG CYREG_B0_UDB08_09_D0
#define clock_cmod_minute_counter__16BIT_D1_REG CYREG_B0_UDB08_09_D1
#define clock_cmod_minute_counter__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB08_09_ACTL
#define clock_cmod_minute_counter__16BIT_F0_REG CYREG_B0_UDB08_09_F0
#define clock_cmod_minute_counter__16BIT_F1_REG CYREG_B0_UDB08_09_F1
#define clock_cmod_minute_counter__A0_A1_REG CYREG_B0_UDB08_A0_A1
#define clock_cmod_minute_counter__A0_REG CYREG_B0_UDB08_A0
#define clock_cmod_minute_counter__A1_REG CYREG_B0_UDB08_A1
#define clock_cmod_minute_counter__D0_D1_REG CYREG_B0_UDB08_D0_D1
#define clock_cmod_minute_counter__D0_REG CYREG_B0_UDB08_D0
#define clock_cmod_minute_counter__D1_REG CYREG_B0_UDB08_D1
#define clock_cmod_minute_counter__DP_AUX_CTL_REG CYREG_B0_UDB08_ACTL
#define clock_cmod_minute_counter__F0_F1_REG CYREG_B0_UDB08_F0_F1
#define clock_cmod_minute_counter__F0_REG CYREG_B0_UDB08_F0
#define clock_cmod_minute_counter__F1_REG CYREG_B0_UDB08_F1
#define clock_cmod_minute_counter__MSK_DP_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_minute_counter__PER_DP_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_mode_state_counter__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB08_09_ACTL
#define clock_cmod_mode_state_counter__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB08_09_CTL
#define clock_cmod_mode_state_counter__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB08_09_CTL
#define clock_cmod_mode_state_counter__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB08_09_CTL
#define clock_cmod_mode_state_counter__16BIT_COUNT_COUNT_REG CYREG_B0_UDB08_09_CTL
#define clock_cmod_mode_state_counter__16BIT_MASK_MASK_REG CYREG_B0_UDB08_09_MSK
#define clock_cmod_mode_state_counter__16BIT_MASK_PERIOD_REG CYREG_B0_UDB08_09_MSK
#define clock_cmod_mode_state_counter__16BIT_PERIOD_MASK_REG CYREG_B0_UDB08_09_MSK
#define clock_cmod_mode_state_counter__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB08_09_MSK
#define clock_cmod_mode_state_counter__CONTROL_AUX_CTL_REG CYREG_B0_UDB08_ACTL
#define clock_cmod_mode_state_counter__CONTROL_REG CYREG_B0_UDB08_CTL
#define clock_cmod_mode_state_counter__CONTROL_ST_REG CYREG_B0_UDB08_ST_CTL
#define clock_cmod_mode_state_counter__COUNT_REG CYREG_B0_UDB08_CTL
#define clock_cmod_mode_state_counter__COUNT_ST_REG CYREG_B0_UDB08_ST_CTL
#define clock_cmod_mode_state_counter__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_mode_state_counter__PER_CTL_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_mode_state_counter__PERIOD_REG CYREG_B0_UDB08_MSK
#define clock_cmod_mode_state_counter_ST__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB08_09_ACTL
#define clock_cmod_mode_state_counter_ST__16BIT_STATUS_REG CYREG_B0_UDB08_09_ST
#define clock_cmod_mode_state_counter_ST__MASK_REG CYREG_B0_UDB08_MSK
#define clock_cmod_mode_state_counter_ST__MASK_ST_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_mode_state_counter_ST__PER_ST_AUX_CTL_REG CYREG_B0_UDB08_MSK_ACTL
#define clock_cmod_mode_state_counter_ST__STATUS_AUX_CTL_REG CYREG_B0_UDB08_ACTL
#define clock_cmod_mode_state_counter_ST__STATUS_CNT_REG CYREG_B0_UDB08_ST_CTL
#define clock_cmod_mode_state_counter_ST__STATUS_CONTROL_REG CYREG_B0_UDB08_ST_CTL
#define clock_cmod_mode_state_counter_ST__STATUS_REG CYREG_B0_UDB08_ST

/* clock_creg */
#define clock_creg_Sync_ctrl_reg__0__MASK 0x01u
#define clock_creg_Sync_ctrl_reg__0__POS 0
#define clock_creg_Sync_ctrl_reg__1__MASK 0x02u
#define clock_creg_Sync_ctrl_reg__1__POS 1
#define clock_creg_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB09_10_ACTL
#define clock_creg_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB09_10_CTL
#define clock_creg_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB09_10_CTL
#define clock_creg_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB09_10_CTL
#define clock_creg_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB09_10_CTL
#define clock_creg_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB09_10_MSK
#define clock_creg_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB09_10_MSK
#define clock_creg_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB09_10_MSK
#define clock_creg_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB09_10_MSK
#define clock_creg_Sync_ctrl_reg__2__MASK 0x04u
#define clock_creg_Sync_ctrl_reg__2__POS 2
#define clock_creg_Sync_ctrl_reg__3__MASK 0x08u
#define clock_creg_Sync_ctrl_reg__3__POS 3
#define clock_creg_Sync_ctrl_reg__4__MASK 0x10u
#define clock_creg_Sync_ctrl_reg__4__POS 4
#define clock_creg_Sync_ctrl_reg__5__MASK 0x20u
#define clock_creg_Sync_ctrl_reg__5__POS 5
#define clock_creg_Sync_ctrl_reg__6__MASK 0x40u
#define clock_creg_Sync_ctrl_reg__6__POS 6
#define clock_creg_Sync_ctrl_reg__7__MASK 0x80u
#define clock_creg_Sync_ctrl_reg__7__POS 7
#define clock_creg_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB09_ACTL
#define clock_creg_Sync_ctrl_reg__CONTROL_REG CYREG_B0_UDB09_CTL
#define clock_creg_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB09_ST_CTL
#define clock_creg_Sync_ctrl_reg__COUNT_REG CYREG_B0_UDB09_CTL
#define clock_creg_Sync_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB09_ST_CTL
#define clock_creg_Sync_ctrl_reg__MASK 0xFFu
#define clock_creg_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB09_MSK_ACTL
#define clock_creg_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB09_MSK_ACTL
#define clock_creg_Sync_ctrl_reg__PERIOD_REG CYREG_B0_UDB09_MSK

/* clock_hh_addr */
#define clock_hh_addr__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define clock_hh_addr__DRQ_NUMBER 2u
#define clock_hh_addr__NUMBEROF_TDS 0u
#define clock_hh_addr__PRIORITY 2u
#define clock_hh_addr__TERMIN_EN 0u
#define clock_hh_addr__TERMIN_SEL 0u
#define clock_hh_addr__TERMOUT0_EN 0u
#define clock_hh_addr__TERMOUT0_SEL 0u
#define clock_hh_addr__TERMOUT1_EN 0u
#define clock_hh_addr__TERMOUT1_SEL 0u

/* clock_hl_addr */
#define clock_hl_addr__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define clock_hl_addr__DRQ_NUMBER 3u
#define clock_hl_addr__NUMBEROF_TDS 0u
#define clock_hl_addr__PRIORITY 2u
#define clock_hl_addr__TERMIN_EN 0u
#define clock_hl_addr__TERMIN_SEL 0u
#define clock_hl_addr__TERMOUT0_EN 0u
#define clock_hl_addr__TERMOUT0_SEL 0u
#define clock_hl_addr__TERMOUT1_EN 0u
#define clock_hl_addr__TERMOUT1_SEL 0u

/* clock_mh_addr */
#define clock_mh_addr__DRQ_CTL CYREG_IDMUX_DRQ_CTL1
#define clock_mh_addr__DRQ_NUMBER 4u
#define clock_mh_addr__NUMBEROF_TDS 0u
#define clock_mh_addr__PRIORITY 2u
#define clock_mh_addr__TERMIN_EN 0u
#define clock_mh_addr__TERMIN_SEL 0u
#define clock_mh_addr__TERMOUT0_EN 0u
#define clock_mh_addr__TERMOUT0_SEL 0u
#define clock_mh_addr__TERMOUT1_EN 0u
#define clock_mh_addr__TERMOUT1_SEL 0u

/* clock_ml_addr */
#define clock_ml_addr__DRQ_CTL CYREG_IDMUX_DRQ_CTL1
#define clock_ml_addr__DRQ_NUMBER 5u
#define clock_ml_addr__NUMBEROF_TDS 0u
#define clock_ml_addr__PRIORITY 2u
#define clock_ml_addr__TERMIN_EN 0u
#define clock_ml_addr__TERMIN_SEL 0u
#define clock_ml_addr__TERMOUT0_EN 0u
#define clock_ml_addr__TERMOUT0_SEL 0u
#define clock_ml_addr__TERMOUT1_EN 0u
#define clock_ml_addr__TERMOUT1_SEL 0u

/* Miscellaneous */
#define BCLK__BUS_CLK__HZ 24000000U
#define BCLK__BUS_CLK__KHZ 24000U
#define BCLK__BUS_CLK__MHZ 24U
#define CY_PROJECT_NAME "boost"
#define CY_VERSION "PSoC Creator  3.3 CP3"
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 19u
#define CYDEV_CHIP_DIE_PSOC4A 11u
#define CYDEV_CHIP_DIE_PSOC5LP 18u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x2E11E069u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 11u
#define CYDEV_CHIP_MEMBER_4C 16u
#define CYDEV_CHIP_MEMBER_4D 7u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 12u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 10u
#define CYDEV_CHIP_MEMBER_4I 15u
#define CYDEV_CHIP_MEMBER_4J 8u
#define CYDEV_CHIP_MEMBER_4K 9u
#define CYDEV_CHIP_MEMBER_4L 14u
#define CYDEV_CHIP_MEMBER_4M 13u
#define CYDEV_CHIP_MEMBER_4N 6u
#define CYDEV_CHIP_MEMBER_4O 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 18u
#define CYDEV_CHIP_MEMBER_5B 17u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5B
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4O_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5B_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_FASTBOOT_ENABLED 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_DMA 0
#define CYDEV_CONFIGURATION_ECC 1
#define CYDEV_CONFIGURATION_IMOENABLED CYDEV_CONFIG_FASTBOOT_ENABLED
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_ENABLE_MASK 0x20u
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DEBUG
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_JTAG_4 1
#define CYDEV_DEBUGGING_DPS_JTAG_5 0
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_DPS_SWD_SWV 6
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_DMA_CHANNELS_AVAILABLE 24u
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_INSTRUCT_CACHE_ENABLED 1
#define CYDEV_INTR_RISING 0x00000001u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_PROTECTION_ENABLE 0
#define CYDEV_STACK_SIZE 0x0800
#define CYDEV_USE_BUNDLED_CMSIS 0
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5.0
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5.0
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5.0
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5.0
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5.0
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5.0
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5.0
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5.0
#define CYDEV_VIO3_MV 5000
#define CYIPBLOCK_ARM_CM3_VERSION 0
#define CYIPBLOCK_P3_ANAIF_VERSION 0
#define CYIPBLOCK_P3_CAPSENSE_VERSION 0
#define CYIPBLOCK_P3_COMP_VERSION 0
#define CYIPBLOCK_P3_DMA_VERSION 0
#define CYIPBLOCK_P3_DRQ_VERSION 0
#define CYIPBLOCK_P3_EMIF_VERSION 0
#define CYIPBLOCK_P3_I2C_VERSION 0
#define CYIPBLOCK_P3_LCD_VERSION 0
#define CYIPBLOCK_P3_LPF_VERSION 0
#define CYIPBLOCK_P3_PM_VERSION 0
#define CYIPBLOCK_P3_TIMER_VERSION 0
#define CYIPBLOCK_P3_USB_VERSION 0
#define CYIPBLOCK_P3_VIDAC_VERSION 0
#define CYIPBLOCK_P3_VREF_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 0
#define CYIPBLOCK_S8_IRQ_VERSION 0
#define CYIPBLOCK_S8_SAR_VERSION 0
#define CYIPBLOCK_S8_SIO_VERSION 0
#define CYIPBLOCK_S8_UDB_VERSION 0
#define DMA_CHANNELS_USED__MASK0 0x0000003Fu
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
