/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "clk.h"
#include "PWM.h"
#include "ADC.h"
#include "sense_aliases.h"
#include "sense.h"
#include "drv_aliases.h"
#include "drv.h"
#include "DMA1_dma.h"
#include "DMA2_dma.h"
#include "seg4_aliases.h"
#include "seg4.h"
#include "seg5_aliases.h"
#include "seg5.h"
#include "DAC.h"
#include "vout_aliases.h"
#include "vout.h"
#include "grid1_aliases.h"
#include "grid1.h"
#include "grid2_aliases.h"
#include "grid2.h"
#include "grid3_aliases.h"
#include "grid3.h"
#include "grid4_aliases.h"
#include "grid4.h"
#include "Clock_1.h"
#include "isr.h"
#include "seg2_aliases.h"
#include "seg2.h"
#include "seg0_aliases.h"
#include "seg0.h"
#include "seg6_aliases.h"
#include "seg6.h"
#include "seg1_aliases.h"
#include "seg1.h"
#include "seg3_aliases.h"
#include "seg3.h"
#include "seg7_aliases.h"
#include "seg7.h"
#include "mode_aliases.h"
#include "mode.h"
#include "up_aliases.h"
#include "up.h"
#include "down_aliases.h"
#include "down.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

